"use client";

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Skeleton } from "@/components/ui/skeleton";
import type { ExplainProjectOutput } from "@/ai/flows/explain-project-flow";

interface ProjectExplanationDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  projectName: string;
  explanation: ExplainProjectOutput | null;
  isLoading: boolean;
}

export function ProjectExplanationDialog({ open, onOpenChange, projectName, explanation, isLoading }: ProjectExplanationDialogProps) {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-xl">
        <DialogHeader>
          <DialogTitle>AI Explanation for: {projectName}</DialogTitle>
          <DialogDescription>
            This explanation was generated by AI based on the project's details.
          </DialogDescription>
        </DialogHeader>
        <div className="space-y-6 py-4 max-h-[60vh] overflow-y-auto pr-2">
          {isLoading ? (
            <div className="space-y-4">
              <Skeleton className="h-4 w-full" />
              <Skeleton className="h-4 w-5/6" />
              <div className="pt-4 space-y-2">
                <Skeleton className="h-4 w-1/3" />
                <Skeleton className="h-4 w-full" />
                <Skeleton className="h-4 w-full" />
                <Skeleton className="h-4 w-full" />
              </div>
              <div className="pt-4">
                <Skeleton className="h-4 w-full" />
              </div>
            </div>
          ) : explanation ? (
            <div className="space-y-4 text-sm">
              <div>
                <h3 className="font-semibold mb-2 text-foreground">Summary</h3>
                <p className="text-muted-foreground">{explanation.summary}</p>
              </div>
              <div>
                <h3 className="font-semibold mb-2 text-foreground">Key Features</h3>
                <ul className="space-y-2 list-disc pl-5 text-muted-foreground">
                  {explanation.features.map((feature, i) => (
                    <li key={i}>{feature}</li>
                  ))}
                </ul>
              </div>
              <div>
                <h3 className="font-semibold mb-2 text-foreground">Tech Stack</h3>
                <p className="text-muted-foreground">{explanation.techStack}</p>
              </div>
            </div>
          ) : (
             <div className="text-center text-muted-foreground py-8">
                Sorry, I was unable to generate an explanation for this project.
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
